// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pos-api/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CashFlowRepository is an autogenerated mock type for the CashFlowRepository type
type CashFlowRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cf
func (_m *CashFlowRepository) Create(ctx context.Context, cf *models.CashFlow) error {
	ret := _m.Called(ctx, cf)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CashFlow) error); ok {
		r0 = rf(ctx, cf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CashFlowRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, limit, offset, cfType, source, startDate, endDate
func (_m *CashFlowRepository) GetAll(ctx context.Context, limit int, offset int, cfType string, source string, startDate *time.Time, endDate *time.Time) ([]models.CashFlow, int64, error) {
	ret := _m.Called(ctx, limit, offset, cfType, source, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.CashFlow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, *time.Time, *time.Time) ([]models.CashFlow, int64, error)); ok {
		return rf(ctx, limit, offset, cfType, source, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, *time.Time, *time.Time) []models.CashFlow); ok {
		r0 = rf(ctx, limit, offset, cfType, source, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CashFlow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, *time.Time, *time.Time) int64); ok {
		r1 = rf(ctx, limit, offset, cfType, source, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, *time.Time, *time.Time) error); ok {
		r2 = rf(ctx, limit, offset, cfType, source, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CashFlowRepository) GetByID(ctx context.Context, id uint) (*models.CashFlow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.CashFlow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.CashFlow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.CashFlow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CashFlow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummary provides a mock function with given fields: ctx, startDate, endDate
func (_m *CashFlowRepository) GetSummary(ctx context.Context, startDate time.Time, endDate time.Time) (float64, float64, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (float64, float64, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) float64); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time, time.Time) error); ok {
		r2 = rf(ctx, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, cf
func (_m *CashFlowRepository) Update(ctx context.Context, cf *models.CashFlow) error {
	ret := _m.Called(ctx, cf)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CashFlow) error); ok {
		r0 = rf(ctx, cf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCashFlowRepository creates a new instance of CashFlowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCashFlowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CashFlowRepository {
	mock := &CashFlowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
