// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	repositories "pos-api/internal/repositories"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DashboardRepository is an autogenerated mock type for the DashboardRepository type
type DashboardRepository struct {
	mock.Mock
}

// GetDashboardStats provides a mock function with given fields: ctx, startDate, endDate
func (_m *DashboardRepository) GetDashboardStats(ctx context.Context, startDate time.Time, endDate time.Time) (*repositories.DashboardStats, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardStats")
	}

	var r0 *repositories.DashboardStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*repositories.DashboardStats, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *repositories.DashboardStats); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.DashboardStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHourlyRevenueTrend provides a mock function with given fields: ctx, startDate, endDate
func (_m *DashboardRepository) GetHourlyRevenueTrend(ctx context.Context, startDate time.Time, endDate time.Time) ([]repositories.RevenueData, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetHourlyRevenueTrend")
	}

	var r0 []repositories.RevenueData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]repositories.RevenueData, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []repositories.RevenueData); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.RevenueData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLowStockCount provides a mock function with given fields: ctx, threshold
func (_m *DashboardRepository) GetLowStockCount(ctx context.Context, threshold int) (int64, error) {
	ret := _m.Called(ctx, threshold)

	if len(ret) == 0 {
		panic("no return value specified for GetLowStockCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, threshold)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, threshold)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, threshold)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLowStockProducts provides a mock function with given fields: ctx, threshold, limit
func (_m *DashboardRepository) GetLowStockProducts(ctx context.Context, threshold int, limit int) ([]repositories.LowStockProduct, error) {
	ret := _m.Called(ctx, threshold, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLowStockProducts")
	}

	var r0 []repositories.LowStockProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repositories.LowStockProduct, error)); ok {
		return rf(ctx, threshold, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repositories.LowStockProduct); ok {
		r0 = rf(ctx, threshold, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.LowStockProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, threshold, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentMethodBreakdown provides a mock function with given fields: ctx, startDate, endDate
func (_m *DashboardRepository) GetPaymentMethodBreakdown(ctx context.Context, startDate time.Time, endDate time.Time) ([]repositories.PaymentMethodData, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentMethodBreakdown")
	}

	var r0 []repositories.PaymentMethodData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]repositories.PaymentMethodData, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []repositories.PaymentMethodData); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.PaymentMethodData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecentTransactions provides a mock function with given fields: ctx, limit
func (_m *DashboardRepository) GetRecentTransactions(ctx context.Context, limit int) ([]repositories.TransactionSummary, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentTransactions")
	}

	var r0 []repositories.TransactionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repositories.TransactionSummary, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repositories.TransactionSummary); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.TransactionSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRevenueTrend provides a mock function with given fields: ctx, startDate, endDate
func (_m *DashboardRepository) GetRevenueTrend(ctx context.Context, startDate time.Time, endDate time.Time) ([]repositories.RevenueData, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetRevenueTrend")
	}

	var r0 []repositories.RevenueData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]repositories.RevenueData, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []repositories.RevenueData); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.RevenueData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopProducts provides a mock function with given fields: ctx, startDate, endDate, limit
func (_m *DashboardRepository) GetTopProducts(ctx context.Context, startDate time.Time, endDate time.Time, limit int) ([]repositories.TopProduct, error) {
	ret := _m.Called(ctx, startDate, endDate, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopProducts")
	}

	var r0 []repositories.TopProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) ([]repositories.TopProduct, error)); ok {
		return rf(ctx, startDate, endDate, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) []repositories.TopProduct); ok {
		r0 = rf(ctx, startDate, endDate, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.TopProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, startDate, endDate, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDashboardRepository creates a new instance of DashboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardRepository {
	mock := &DashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
