// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pos-api/internal/models"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// InventoryLogRepository is an autogenerated mock type for the InventoryLogRepository type
type InventoryLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log
func (_m *InventoryLogRepository) Create(ctx context.Context, log *models.InventoryLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InventoryLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessAdjustment provides a mock function with given fields: ctx, log, product
func (_m *InventoryLogRepository) ProcessAdjustment(ctx context.Context, log *models.InventoryLog, product *models.Product) error {
	ret := _m.Called(ctx, log, product)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAdjustment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InventoryLog, *models.Product) error); ok {
		r0 = rf(ctx, log, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByProductID provides a mock function with given fields: ctx, productID, limit, offset
func (_m *InventoryLogRepository) GetByProductID(ctx context.Context, productID uint, limit int, offset int) ([]models.InventoryLog, int64, error) {
	ret := _m.Called(ctx, productID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductID")
	}

	var r0 []models.InventoryLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]models.InventoryLog, int64, error)); ok {
		return rf(ctx, productID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []models.InventoryLog); ok {
		r0 = rf(ctx, productID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.InventoryLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, productID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, productID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAll provides a mock function with given fields: ctx, limit, offset, logType, source, startDate, endDate
func (_m *InventoryLogRepository) GetAll(ctx context.Context, limit int, offset int, logType string, source string, startDate *time.Time, endDate *time.Time) ([]models.InventoryLog, int64, error) {
	ret := _m.Called(ctx, limit, offset, logType, source, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.InventoryLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, *time.Time, *time.Time) ([]models.InventoryLog, int64, error)); ok {
		return rf(ctx, limit, offset, logType, source, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, *time.Time, *time.Time) []models.InventoryLog); ok {
		r0 = rf(ctx, limit, offset, logType, source, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.InventoryLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, *time.Time, *time.Time) int64); ok {
		r1 = rf(ctx, limit, offset, logType, source, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, *time.Time, *time.Time) error); ok {
		r2 = rf(ctx, limit, offset, logType, source, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStats provides a mock function with given fields: ctx, startDate, endDate
func (_m *InventoryLogRepository) GetStats(ctx context.Context, startDate *time.Time, endDate *time.Time) (map[string]int64, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) (map[string]int64, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) map[string]int64); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryLogRepository creates a new instance of InventoryLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryLogRepository {
	mock := &InventoryLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
