// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pos-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// PaymentMethodRepository is an autogenerated mock type for the PaymentMethodRepository type
type PaymentMethodRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, pm
func (_m *PaymentMethodRepository) Create(ctx context.Context, pm *models.PaymentMethod) error {
	ret := _m.Called(ctx, pm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentMethod) error); ok {
		r0 = rf(ctx, pm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PaymentMethodRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActive provides a mock function with given fields: ctx
func (_m *PaymentMethodRepository) GetActive(ctx context.Context) ([]models.PaymentMethod, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 []models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.PaymentMethod, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.PaymentMethod); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *PaymentMethodRepository) GetAll(ctx context.Context) ([]models.PaymentMethod, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.PaymentMethod, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.PaymentMethod); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PaymentMethodRepository) GetByID(ctx context.Context, id uint) (*models.PaymentMethod, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.PaymentMethod, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.PaymentMethod); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, pm
func (_m *PaymentMethodRepository) Update(ctx context.Context, pm *models.PaymentMethod) error {
	ret := _m.Called(ctx, pm)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentMethod) error); ok {
		r0 = rf(ctx, pm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentMethodRepository creates a new instance of PaymentMethodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodRepository {
	mock := &PaymentMethodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
