// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	repositories "pos-api/internal/repositories"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

// GetProductReport provides a mock function with given fields: ctx, startDate, endDate, limit
func (_m *ReportRepository) GetProductReport(ctx context.Context, startDate time.Time, endDate time.Time, limit int) ([]repositories.ProductReport, error) {
	ret := _m.Called(ctx, startDate, endDate, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetProductReport")
	}

	var r0 []repositories.ProductReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) ([]repositories.ProductReport, error)); ok {
		return rf(ctx, startDate, endDate, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) []repositories.ProductReport); ok {
		r0 = rf(ctx, startDate, endDate, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.ProductReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, startDate, endDate, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSalesByHour provides a mock function with given fields: ctx, startDate, endDate
func (_m *ReportRepository) GetSalesByHour(ctx context.Context, startDate time.Time, endDate time.Time) ([]repositories.HourlySales, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesByHour")
	}

	var r0 []repositories.HourlySales
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]repositories.HourlySales, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []repositories.HourlySales); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.HourlySales)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSalesReport provides a mock function with given fields: ctx, startDate, endDate
func (_m *ReportRepository) GetSalesReport(ctx context.Context, startDate time.Time, endDate time.Time) ([]repositories.SalesReport, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesReport")
	}

	var r0 []repositories.SalesReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]repositories.SalesReport, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []repositories.SalesReport); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.SalesReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSalesSummary provides a mock function with given fields: ctx, startDate, endDate
func (_m *ReportRepository) GetSalesSummary(ctx context.Context, startDate time.Time, endDate time.Time) (*repositories.SalesSummary, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesSummary")
	}

	var r0 *repositories.SalesSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*repositories.SalesSummary, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *repositories.SalesSummary); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.SalesSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockValue provides a mock function with given fields: ctx
func (_m *ReportRepository) GetStockValue(ctx context.Context) (*repositories.StockValue, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStockValue")
	}

	var r0 *repositories.StockValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*repositories.StockValue, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *repositories.StockValue); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.StockValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
