// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "pos-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// StoreSettingRepository is an autogenerated mock type for the StoreSettingRepository type
type StoreSettingRepository struct {
	mock.Mock
}

// GetSettings provides a mock function with given fields: ctx
func (_m *StoreSettingRepository) GetSettings(ctx context.Context) (*models.StoreSetting, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *models.StoreSetting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.StoreSetting, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.StoreSetting); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StoreSetting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertSettings provides a mock function with given fields: ctx, settings
func (_m *StoreSettingRepository) UpsertSettings(ctx context.Context, settings *models.StoreSetting) (*models.StoreSetting, error) {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSettings")
	}

	var r0 *models.StoreSetting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.StoreSetting) (*models.StoreSetting, error)); ok {
		return rf(ctx, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.StoreSetting) *models.StoreSetting); ok {
		r0 = rf(ctx, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StoreSetting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.StoreSetting) error); ok {
		r1 = rf(ctx, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStoreSettingRepository creates a new instance of StoreSettingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreSettingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreSettingRepository {
	mock := &StoreSettingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
